# Assignment Task 2 - Perform 2 tensor operations on tensors of 3,4,5 dim

### SAHIL AMRITKAR
### 20BRS1180  


In [38]:
import numpy as np
import random

In [39]:
#RELU
def naive_relu(x):
    shape=x.shape
    new=[]
    for i in np.nditer(x):
        new.append(max(0, i))
    new=np.reshape(new, shape)
    return new

In [40]:
#ADD
def naive_add(x, y):
    shape=x.shape
    new=[]
    for i,j in zip(np.nditer(x), np.nditer(y)):
        new.append(i+j)
    new=np.reshape(new, shape)
    return new

In [41]:
# 3 dimension data- Random Numbers
dim3=np.random.randint(low=-10, high=11, size=(1, 3, 3))
print("dim:",dim3.ndim)
print("shape:",dim3.shape)

dim: 3
shape: (1, 3, 3)


In [42]:
# 4 dimension data- Random Numbers
dim4=np.random.randint(low=-10, high=11, size=(1, 1, 3, 3))
print("dim:",dim4.ndim)
print("shape:",dim4.shape)

dim: 4
shape: (1, 1, 3, 3)


In [43]:
# 5 dimension data- Random Numbers
dim5=np.random.randint(low=-10, high=11, size=(1, 1, 1, 3, 3))
print("dim:",dim5.ndim)
print("shape:",dim5.shape)

dim: 5
shape: (1, 1, 1, 3, 3)


In [44]:
#relu on 3 dim
print("before:\n", dim3)
dim3=naive_relu(dim3)
print("after relu:\n", dim3)

before:
 [[[  0   0  -1]
  [  4   7 -10]
  [  9  -2  -5]]]
after relu:
 [[[0 0 0]
  [4 7 0]
  [9 0 0]]]


In [45]:
#relu on 4 dim
print("before:\n", dim4)
dim4=naive_relu(dim4)
print("after relu:\n", dim4)

before:
 [[[[-7  2 -3]
   [ 7  9  5]
   [ 0  5 -7]]]]
after relu:
 [[[[0 2 0]
   [7 9 5]
   [0 5 0]]]]


In [46]:
#relu on 5 dim
print("before:\n", dim5)
dim5=naive_relu(dim5)
print("after relu:\n", dim5)

before:
 [[[[[ 4 -1  1]
    [ 8  9 -7]
    [-8 -2 10]]]]]
after relu:
 [[[[[ 4  0  1]
    [ 8  9  0]
    [ 0  0 10]]]]]


In [47]:
#Adding
print("Adding 2 3dim:\n", naive_add(dim3, dim3))
print("Adding 2 4dim:\n", naive_add(dim4, dim4))
print("Adding 2 5dim:\n", naive_add(dim5, dim5))

Adding 2 3dim:
 [[[ 0  0  0]
  [ 8 14  0]
  [18  0  0]]]
Adding 2 4dim:
 [[[[ 0  4  0]
   [14 18 10]
   [ 0 10  0]]]]
Adding 2 5dim:
 [[[[[ 8  0  2]
    [16 18  0]
    [ 0  0 20]]]]]
